language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TEST_TYPE="tests" INSTALL_TYPE="testing"
  - TEST_TYPE="tests" INSTALL_TYPE="testing_sdist"
jobs:
  include:
  - python: "3.7"
    env: TEST_TYPE="pre-commit" INSTALL_TYPE="dev_precommit"
cache: pip
sudo: true
services:
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-scipy
      - python3-h5py
before_install:
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U scipy decorator
  - sudo pip3 install symmetry-representation
  - sudo service postgresql restart
install:
  - ./.travis-data/install_script.sh
script:
  - ./.travis-data/test_script.sh
