language: python
python:
  - "2.7"
  - "3.6"
cache: pip
sudo: true
dist: xenial
services:
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-scipy
      - python3-h5py
  postgresql: "9.5"
before_install:
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U scipy decorator
  - sudo pip3 install symmetry-representation
install:
  - pip install -U pip wheel setuptools
  - pip install git+https://github.com/aiidateam/aiida_core.git#egg=aiida-core
  - pip install git+https://github.com/greschd/aiida-tools#egg=aiida-tools
  - pip install git+https://github.com/greschd/aiida_symmetry_representation#egg=aiida-symmetry-representation
  - pip install git+https://github.com/greschd/aiida_pytest@develop#egg=aiida-pytest
  - pip install .[test,pre-commit]
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
